name: CD DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Github Repository 가져오기
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: 서브묘듈 초기화하기
        run: git submodule update --init --recursive

      - name: 서브묘듈 main에 최신화하기
        run: git submodule foreach git pull origin main

      - name: 자바 17버전 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/WearWeather-BackEnd/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/WearWeather-BackEnd/current
            mkdir /home/ubuntu/WearWeather-BackEnd/current
            mv /home/ubuntu/WearWeather-BackEnd/tobe/project.jar /home/ubuntu/WearWeather-BackEnd/current/project.jar
            cd /home/ubuntu/WearWeather-BackEnd/current
            sudo fuser -k -n tcp 8080 || true
            JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }} nohup java -jar project.jar --spring.profiles.active=prod > ./output.log 2>&1 &
            rm -rf /home/ubuntu/WearWeather-BackEnd/tobe